const COMPARE = "COMPARE";
const SWAP = "SWAP";
const SWAP_DONE = "SWAP_DONE";
const SINGLE_DONE = "SINGLE_DONE";
const FINISHED = "FINISHED";
const PICK_PIVOT = "PICK_PIVOT";

export {COMPARE, SWAP, SWAP_DONE, SINGLE_DONE, FINISHED, PICK_PIVOT};