const colorChart = {
  PINK: '#FBBCBF',
  LIGHT_PINK: '#FCE2E6',
  SKY_BLUE: '#CCF5FA',
};

const DEFAULT_NODE_GAP = 50;

const DEFAULT_SECONDS = 400;
const UI_DEFAULT_SECONDS = 100;
const UI_DELAY_SECONDS = 4;
const INCREASED_UI_SECONDS = 500;

const MIN_LIST_LENGTH = 5;
const MAX_LIST_LENGTH = 10;

const MIN_NUMBER_RANGE = 0;
const MAX_NUMBER_RANGE = 100;

const LEFT_NODE_INDEX = 0;
const RIGHT_NODE_INDEX = 1;
